name: tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  unit_test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        features: ["", "scalar"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run unit tests
        run: cargo test --no-default-features --features "${{ matrix.features }}"

  unit_test_nightly:
    strategy:
      matrix:
        os: [ubuntu-latest]
        features: ["", "scalar"]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Run unit tests
        run: cargo test --no-default-features --features "${{ matrix.features }}"

  system-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        features: ["", "scalar"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: build project
        run: cargo build

      - name: Run system tests
        run: |
          chmod +x tests/system_testing/run.sh
          tests/system_testing/run.sh